/**
 * The history page's data for one finished season: src/assets/history/{season}-{gameType}.json, like 20252026-2.json,
 * generated by build-season-data.js from the NHL stats API's per game rows (see "History data" in docs/nhl-api.md).
 *
 * It holds the inputs of the HokMob rating, not the ratings, so a change to the formula shows up on the history page
 * without regenerating the file. Each table is columnar, an object of equally long arrays, one per field, so a field
 * name is written once rather than on every row. A skater or goalie row points at its player and game by their index
 * in those tables. The field names are the stats API's.
 */
export interface SeasonHistory {
  /** The file format's version, 1. */
  version: number;
  /** Like 20252026. */
  season: number;
  /** 2 for the regular season, 3 for the playoffs. */
  gameType: number;
  /** The day the file was generated, like "2026-09-24". */
  generated: string;
  games: SeasonHistoryGames;
  players: SeasonHistoryPlayers;
  skaters: SeasonHistorySkaterRows;
  goalies: SeasonHistoryGoalieRows;
}

/** Every game of the season, in game ID order. */
export interface SeasonHistoryGames {
  id: number[];
  /** Like "2025-10-07". */
  date: string[];
  homeTeamId: number[];
  awayTeamId: number[];
  homeScore: number[];
  awayScore: number[];
}

/** Every player with a game in the file, in player ID order. */
export interface SeasonHistoryPlayers {
  id: number[];
  /** Like "Connor McDavid". */
  name: string[];
  /** C, L, R, D or G. A player has the same position in every game of a season. */
  position: string[];
}

/** The columns every skater and goalie row has. */
export interface SeasonHistoryRows {
  /** The player's index in the players table. */
  player: number[];
  /** The game's index in the games table. */
  game: number[];
  /** 1 when the player's team was the home team, 0 when it was the away team. */
  home: number[];
}

/**
 * A skater's stat line in each game. The same fields the player page's recent games merge from the stats API reports
 * (NhlStatsController.GetPlayerStats), plus the 5v5 Corsi and Fenwick counts.
 */
export interface SeasonHistorySkaterRows extends SeasonHistoryRows {
  /** Seconds. */
  timeOnIcePerGame: number[];
  goals: number[];
  assists: number[];
  plusMinus: number[];
  penaltyMinutes: number[];
  ppGoals: number[];
  shots: number[];
  /** 0 to 1, and 0 without faceoffs. */
  faceoffWinPct: number[];
  totalPrimaryAssists: number[];
  totalSecondaryAssists: number[];
  ppAssists: number[];
  hits: number[];
  blockedShots: number[];
  takeaways: number[];
  giveaways: number[];
  totalFaceoffs: number[];
  penaltiesDrawn: number[];
  /** The 5v5 shot attempts (Corsi) for and against the skater's team while the skater was on the ice. Not rated. */
  satFor: number[];
  satAgainst: number[];
  /** The unblocked shot attempts (Fenwick) for and against, the same way. Not rated yet. */
  usatFor: number[];
  usatAgainst: number[];
}

/**
 * A goalie's stat line in each game. The saves and shots against are the sums of the three strengths.
 */
export interface SeasonHistoryGoalieRows extends SeasonHistoryRows {
  /** Seconds. */
  timeOnIce: number[];
  evSaves: number[];
  evShotsAgainst: number[];
  ppSaves: number[];
  ppShotsAgainst: number[];
  shSaves: number[];
  shShotsAgainst: number[];
}

/** A player of a rated season. */
export interface HistoryPlayer {
  id: number;
  name: string;
  /** C, L, R, D or G. */
  position: string;
}

/** A game of a rated season. */
export interface HistoryGame {
  id: number;
  /** Like "2025-10-07". */
  date: string;
  homeTeamId: number;
  awayTeamId: number;
  homeScore: number;
  awayScore: number;
}

/** The position groups the history page splits ratings by: forwards, defensemen and goalies. */
export type PositionGroup = "F" | "D" | "G";

/**
 * One player's HokMob rating in one game. The player and the game are shared objects, one per player and per game.
 */
export interface RatedGame {
  player: HistoryPlayer;
  game: HistoryGame;
  /** The player's team in this game, which changes when they're traded. */
  teamId: number;
  opponentId: number;
  position: PositionGroup;
  rating: number;
  /**
   * Only for a game rated 10: the rating before it was capped (StatsUtils.getSkaterRawRating or getGoalieRawRating), like 11.4, which ranks
   * the season's 10s among themselves.
   */
  uncappedRating?: number;
  /** Seconds. */
  timeOnIce: number;
}

/**
 * A season's history, rated: every game's rating, with the goalies who faced no shots left out, since the rating
 * gives them 0 for a game they took no part in.
 */
export interface RatedSeason {
  season: number;
  gameType: number;
  players: HistoryPlayer[];
  games: HistoryGame[];
  /** Skaters and goalies, in game order. */
  ratedGames: RatedGame[];
}
